# Site settings
title: 400dama blog
description: "DunDunDunDun Ge~"
baseurl: ""
url: ""

# User settings
username: 400dama
user_title: 400dama
email: gotenks9002@gmail.com
github_username: 400dama
profile_picture: "https://gitee.com/BugaoSion/dotfiles/raw/master/blog_temp/aniki-six.png"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1

    - title: my posts
      url: /posts
      key_trigger: 2

    - title: series
      url: /series
      key_trigger: 3

    - title: tags
      url: /tags
      key_trigger: 4

    - title: about me
      url: /about
      key_trigger: 5

  section_2:
    - title: github
      url: http://www.github.com/400dama
      new_tab: true
      key_trigger: g

    - title: gitee
      url: https://gitee.com/BugaoSion
      new_tab: true
      key_trigger: e

    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
# projects:
#   - name: fluany
#     url: https://github.com/fluany/fluany
#   - name: vim-frontend
#     url: https://github.com/victorvoid/vim-frontend
#   - name: generator-capybara
#     url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
